spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/smalleducator
    username: wild-username
    password: wild_password
server:
  servlet:
    context-path: /api
